# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('sub_title', models.CharField(max_length=100, verbose_name='Subtitulo')),
                ('text', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('image', models.ImageField(blank=True, null=True, upload_to='noticias/images', verbose_name='Imagem')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
            },
        ),
    ]
