# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20170503_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tags para facilitar a busca no site'),
        ),
    ]
