# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='credits_image',
            field=models.TextField(blank=True, verbose_name='Credits'),
        ),
    ]
