# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='expired_at',
            field=models.DateTimeField(null=True, verbose_name='Data de expiração da notícia'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='legend_image',
            field=models.CharField(max_length=100, null=True, verbose_name='Legenda da imagem'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='Data de publicação'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='tag',
            field=models.CharField(max_length=100, null=True, verbose_name='Tags para facilitar a busca no site'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='sub_title',
            field=models.CharField(max_length=100, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
