# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20170504_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='summary',
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição do album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
