# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20170504_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidade',
            name='photos',
        ),
        migrations.AddField(
            model_name='comunidade',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Album', verbose_name='Album de Fotos'),
        ),
    ]
