# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20170504_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidade',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='content.Album', verbose_name='Album de Fotos'),
        ),
    ]
