# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20170504_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='notice_origin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fonte da notícia'),
        ),
    ]
