# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20170505_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_noticia', to='content.Album', verbose_name='Album de Fotos'),
        ),
    ]
