# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_noticia_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Fotografo'),
        ),
    ]
