# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20170505_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título do evento')),
                ('event_date', models.DateTimeField(blank=True, verbose_name='Data do evento')),
                ('text', tinymce.models.HTMLField(verbose_name='Texto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='timeline/images', verbose_name='Imagem de apresentação')),
                ('legend_image', models.CharField(blank=True, max_length=200, null=True, verbose_name='Legenda da imagem')),
            ],
            options={
                'verbose_name': 'Evento da linha do tempo',
                'ordering': ['-event_date'],
                'verbose_name_plural': 'Eventos da linha do tempo',
            },
        ),
    ]
