# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20170612_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='event_date',
            field=models.DateField(blank=True, verbose_name='Data do evento'),
        ),
    ]
