# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20170612_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='text',
            field=models.TextField(verbose_name='Texto'),
        ),
    ]
