# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20170612_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('image', models.ImageField(upload_to='youtube_channel/images', verbose_name='Imagem de apresentação do canal')),
                ('slug', models.SlugField(max_length=500, null=True, verbose_name='Identificador')),
                ('api_key', models.CharField(help_text='API KEY do google, veja como obte-lá https://developers.google.com/youtube/v3/getting-started', max_length=500, verbose_name='API Key')),
                ('channel_link', models.CharField(help_text='Link do canal no youtube, exemplo: https://www.youtube.com/user/crashcourse', max_length=500, verbose_name='Link do canal')),
                ('playlist_link', models.CharField(help_text='Link da playlist no youtube, exemplo: https://www.youtube.com/playlist?list=PL6_h4dV9kuuIOBDKgxu3q9DpvvJFZ6fB5', max_length=500, verbose_name='Link da playlist')),
                ('max_results', models.IntegerField(default=9, help_text='O valor padrão é 9', verbose_name='Máximo de resultados por página')),
                ('default_tab', models.CharField(choices=[('UP', 'Uploads'), ('PL', 'Playlists'), ('FE', 'Featured')], default='UP', max_length=2)),
                ('video_display_mode', models.CharField(choices=[('PO', 'popup'), ('LK', 'link'), ('IN', 'inline')], default='PO', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Galeria de vídeos do youtube',
                'verbose_name_plural': 'Galerias de vídeos do youtube',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['event_date'], 'verbose_name': 'Evento da linha do tempo', 'verbose_name_plural': 'Eventos da linha do tempo'},
        ),
    ]
