# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20170621_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubechannel',
            name='playlist_link',
            field=models.CharField(blank=True, help_text='Link da playlist no youtube, exemplo: https://www.youtube.com/playlist?list=PL6_h4dV9kuuIOBDKgxu3q9DpvvJFZ6fB5', max_length=500, null=True, verbose_name='Link da playlist'),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=500, null=True, verbose_name='Identificador'),
        ),
    ]
