# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_categoryfaq_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True, verbose_name='Identificador'),
        ),
    ]
