# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20170628_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(help_text='Resposta para a pergunta que será apresentada no site', max_length=500, verbose_name='Resposta'),
        ),
    ]
