# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_auto_20170628_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='content.CategoryFaq', verbose_name='Categoria'),
        ),
    ]
