# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_auto_20170628_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='short_text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_frequentes', to='content.CategoryFaq', verbose_name='Categoria'),
        ),
    ]
