# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 14:37
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_auto_20170629_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidade',
            name='about',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='short_text',
        ),
        migrations.AddField(
            model_name='comunidade',
            name='text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='Sobre a comunidade'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
