# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20170629_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='album',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/images', verbose_name='Imagem de capa para a Notícia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='legend_image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Creditos da imagem de capa para a Notícia'),
        ),
    ]
