# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_noticia_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubechannel',
            name='api_key',
        ),
    ]
