# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('content', '0035_remove_youtubechannel_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='author',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comunidade',
            name='album',
        ),
        migrations.AddField(
            model_name='comunidade',
            name='galery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galaria', to='photologue.Gallery', verbose_name='Album de Fotos'),
        ),
        migrations.AddField(
            model_name='comunidade',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=500, null=True, verbose_name='Identificador'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
