# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_auto_20170629_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-published_at', 'legend_image'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AlterField(
            model_name='comunidade',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=500, null=True, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=500, null=True, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtítulo'),
        ),
    ]
