# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20170703_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Somente as notícias marcadas como públicas serão apresentadas no site.', verbose_name='É Pública ?'),
        ),
    ]
