# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_noticia_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidade',
            name='lat_long',
        ),
        migrations.AddField(
            model_name='comunidade',
            name='lat',
            field=models.CharField(blank=True, max_length=100, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='comunidade',
            name='long',
            field=models.CharField(blank=True, max_length=100, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='categoryfaq',
            name='slug',
            field=models.SlugField(help_text="'slug' é um identificador único que será mostrado na url", max_length=500, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='comunidade',
            name='slug',
            field=models.SlugField(help_text="'slug' é um identificador único que será mostrado na url", max_length=500, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.SlugField(help_text="'slug' é um identificador único que será mostrado na url", max_length=500, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(help_text="'slug' é um identificador único que será mostrado na url", max_length=500, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='slug',
            field=models.SlugField(help_text="'slug' é um identificador único que será mostrado na url", max_length=500, unique=True, verbose_name='Identificador'),
        ),
    ]
