# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_auto_20170706_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.SlugField(blank=True, help_text="'slug' é um identificador único que será mostrado na url", max_length=500, null=True, unique=True, verbose_name='Identificador'),
        ),
    ]
