# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_comunidade_kmz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidade',
            name='kmz',
        ),
    ]
