# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0046_remove_comunidade_kmz'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtaReuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título da ata de reunião')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='ata_reuniao/%Y/%m/%d/')),
                ('date_ata_reuniao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Ata de reunião')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Ata de Reunião',
                'verbose_name_plural': 'Atas de Reuniões',
                'ordering': ['title'],
            },
        ),
    ]
