# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_auto_20170707_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atareuniao',
            options={'ordering': ['-date_ata_reuniao'], 'verbose_name': 'Ata de Reunião', 'verbose_name_plural': 'Atas de Reuniões'},
        ),
    ]
