# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_auto_20170707_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='tag',
        ),
        migrations.AddField(
            model_name='noticia',
            name='credits_image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Creditos da imagem'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='legend_image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Legenda da Imagem'),
        ),
    ]
